-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args:
        - --fix=no
    -   id: flake8
        args:
        - --exclude=docs/conf.py
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.0.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
