sudo: false
language: python
virtualenv:
  system_site_packages: true
matrix:
  include:
    - os: linux
      env: DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - os: osx
      language: generic  # workaround for osx (travis-ci #7132)
      env: PYTHON_VERSION="2.7" COVERAGE="false"
    - os: osx
      language: generic  # workaround for osx (travis-ci #7132)
      env: PYTHON_VERSION="3.6" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
install:
  - source tests/travis_install.sh
  - pip install -U pip
  - pip install -U -r requirements.txt -r test-requirements.txt
  - pip install django
  - pip install cookiecutter
  - pip install tox
  - if [[ "$DISTRIB" == "conda" ]]; then conda install -y virtualenv; fi
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - pip list
  - export SKIP_GENERATE_AUTHORS=1
  - export SKIP_WRITE_GIT_CHANGELOG=1
script:
  - python setup.py egg_info
  - tox
  - pip install -e .
  # postpone installation until here due to problem with Spinx and Python < 3.5
  - pip install sphinx
  - ./tests/system_test.sh
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then py.test tests; coveralls || echo "failed"; fi
cache:
  apt: true
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3b31825a7e1c501c9c1f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never
