sudo: false
language: python
virtualenv:
  system_site_packages: true
matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.4
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py34" COVERAGE="true"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
    - os: osx
      language: generic  # workaround for osx (travis-ci #7132)
      env: PYTHON_VERSION="3.6" COVERAGE="false"
  allow_failures:
    # python=3.7 has currently a conflict with virtualenv in conda
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - rm -rf .coverage  # Avoid information carried from one run to the other
script:
  - pip list
  - python setup.py develop
  - tox -e all -- -n 31 --durations 10
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  # We need to call py.tes again so that Coveralls shows the source code online
  - if [[ "$COVERAGE" == "true" ]]; then (coverage combine .coverage && coveralls) || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3b31825a7e1c501c9c1f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never
git:
  depth: 99999   # avoids shallow checkouts which interfere with setuptools_scm way of determining PyScaffold's version
