# Use only for PyScaffold development. Execute `conda env create -f environment.yaml`
name: pyscaffold
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - flake8
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-virtualenv
  - pytest-fixture-config
  - pytest-shutil
  - pre_commit
